### ISSUE TITLE
Web platform

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#10]
## 📋 Epic
A web application to allow users to interact with the underlying event and driver systems.

## Description
The web platform should allow the creation of new events after the user has fulfilled certain fields. It acts as a bridge between the users and the event services (rating, creation, etc.).
Another functionality provided will be to apply to be a company driver, as well as an administrative part where drivers can be accepted.

## List of requirements
[**Events**]
- [ ] Connect to several APIs (Location, Notification, Rating, Creation, Event) #25 
- [ ] Collect a list of predefined user-input #26 
- [ ] Allow requests for new events #27
- [ ] Allow users to finish and provide feedback on events #28
- [ ] Allow users to receive notifications on event status #29

[**Drivers**]
- [ ] Connect to the driver API #30
- [ ] Collect new driver's data #31
- [ ] Administrative part where you can query all current applications #32
- [ ] Accept current application(s) to the system #33
- [ ] Validate input data #34
- [ ] Create Dockerfile #35

## Acceptance Criteria
1. Able to connect to several APIs
1. Validate user data
1. Dockerfile included
