### ISSUE TITLE
Rating service

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#11]
## 📋 Epic
A service that allows a past event to be rated.

## Description
This service should be able to receive and store feedback from a user's previous events. It should also allow displaying received feedback on specific events (querying specific feedback).

## List of requirements
- [x] Subscribe to "**event.feedback**" queue while listening to either an "Add" or "Get" command #36 
- [x] Connect to a SQL Database #37 
- [ ] Create unit tests #68 

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
