### ISSUE TITLE
Notification service

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#12]
## 📋 Epic
A service that allows notifications to be sent to the user.

## Description
This service should be able to receive status from other services and provide a user with a human-friendly message.

## List of requirements
- [x] Implement a RESTful endpoint to fetch new notifications #38 
- [x] Implement a RESTful endpoint to mark notification(s) as read #39 
- [x] Subscribe to meaningful services (creation service) #40 
- [x] Connect to a SQL Database #41 
- [ ] Create unit tests #69

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
