### ISSUE TITLE
Location service

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#13]
## 📋 Epic
A service that enables the discovery of existing locations in the system.

## Description
This service should be able to hold a CSV file with locations information that can be requested by a Web API endpoint.

## List of requirements
- [x] Implement a RESTful endpoint to fetch existing locations #42
- [x] Transform data from CSV to JSON #43
- [x] Read from a CSV file #44
- [ ] Create unit tests #70

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
