### ISSUE TITLE
Creation service

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#14]
## 📋 Epic
Needs: #9 
A service that facilitates the creation of new events.

## Description
This service should be able to receive a request to create a new event. It should then orchestrate the entire process of announcing that a new event request was made (to be read by the subscribed service), finding out if by the event times there are drivers and cars available.

## List of requirements
- [x] Implement an "**events**" queue which would subscribe to messages which have the "**events.add**" #45 
- [x] Create a request to the Connector for available cars using the "**connector.requests**" queue with a "getAvailableCars" command #46 
- [x] Send a message to the "**driver.find**" queue with enough data for it to find suitable drivers #47
- [ ] Create tests #71

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
