### ISSUE TITLE
Driver service

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#15]
## 📋 Epic
A service keeps information about currently hired drivers and can find a suitable match for an event.

## Description
This service should be able to receive hiring applications from new drivers. It should also allow for the adding of newly hired drivers. At last, it helps with finding matching drivers to a requested set of dates.

## List of requirements
- [x] Implement a RESTful endpoint to add new hiring applications #48 
- [x] Implement a RESTful endpoint get all hiring applications #49 
- [x] Implement a RESTful endpoint approve a hiring application #50 
- [x] Subscribe to "**drivers.find**" queue in order to start a job for searching an appropriate driver #51 
- [x] Connect to a SQL Database #52 
- [ ] Create unit tests #72

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
