### ISSUE TITLE
Logger service

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#17]
## 📋 Epic
A service that keeps logs of the several services on a file and on the screen.

## Description
This service should be able to subscribe to a "logger" queue, on which other services would publish messages.

## List of requirements
- [x] Implement a "**logger**" queue which would subscribe to messages which several services would publish #53
- [x] Receive commands in order to format the logs in different formats as needed #54
- [x] Have different queues for "info", "warning" and "danger" #55
- [x] Print to the screen the most severe logs #56
- [ ] Create unit tests #73

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to write information to a file
1. Able to transfer data between systems
1. Dockerfile included
