### ISSUE TITLE
Event service

### ISSUE THREAD

**Issue by elit0451** [elit0451/SI-FinalProject#18]
## 📋 Epic
A service whose purpose is to orchestrate requests regarding events.

## Description
This service should be able to receive requests for giving feedback and event creation. It should take these requests and add an appropriate command and publish them in the "**event.add**" and "**event.feedback**" query.

## List of requirements
- [x] Implement a RESTful endpoint to add a new rating #57
- [x] Implement a RESTful endpoint get a specific rating #58 
- [x] Implement a RESTful endpoint to add a new event #59 
- [x] Publish newly received requests to their appropriate queues #60 
- [x] Keep a database record of all events and update them accordingly #61 
- [x] Connect to a SQL Database #62 
- [ ] Create unit tests #74

## Acceptance Criteria
1. Has unit tests
1. _Has integration tests_
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
