### ISSUE TITLE
RMI Connector

### ISSUE THREAD

**Issue by davi7725** [elit0451/SI-FinalProject#9]
## 📋 Epic
A connector to be used between the legacy system and the MOM infrastructure.

## Description
The connector should create an RMI connection to the legacy system and transform the incoming data into JSON format. After processing it should send the JSON formatted data onto a queue to later be consumed.
It should work in an asynchronous way.

## List of requirements
- [x] Implement command pattern to distinguish requests between adding a booking or getting available cars #19 
- [x] Should connect to RMI Backend #20
- [x] Should be able to execute `getAvailableCars()` and `addNewBooking()` from the monolith #21
- [x] Process data into JSON format (coming from `getAvailableCars()`) #22
- [x] Write to the "**cars.available**" queue what is returned from `getAvailableCars()` #23
- [x] Create Dockerfile #24 
- [ ] Create unit tests #67

## Acceptance Criteria
1. Has unit tests
1. Able to transform information to JSON
1. Able to transfer data between systems
1. Dockerfile included
